apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "traffic-report.fullname" . }}
  labels:
    {{- include "traffic-report.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "traffic-report.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "traffic-report.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "traffic-report.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh"]
          args:
            - -c
            - |
              # Patch app.py to use environment variables
              sed -i 's/share=True/share=os.environ.get("GRADIO_SHARE", "false").lower() == "true"/g' /app/app.py
              sed -i 's/server_name="0.0.0.0"/server_name=os.environ.get("GRADIO_SERVER_NAME", "0.0.0.0")/g' /app/app.py
              # Ensure os import is available
              grep -q "import os" /app/app.py || sed -i '1i import os' /app/app.py
              # Launch the application
              python /app/app.py
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: GRADIO_SERVER_PORT
              value: {{ .Values.env.GRADIO_SERVER_PORT | quote }}
            - name: GRADIO_SERVER_NAME
              value: {{ .Values.env.GRADIO_SERVER_NAME | quote }}
            - name: GRADIO_SHARE
              value: {{ .Values.env.GRADIO_SHARE | quote }}
            - name: GRADIO_ALLOW_FLAGGING
              value: {{ .Values.env.GRADIO_ALLOW_FLAGGING | quote }}
            - name: GRADIO_ANALYTICS_ENABLED
              value: {{ .Values.env.GRADIO_ANALYTICS_ENABLED | quote }}
            - name: GRADIO_THEME
              value: {{ .Values.env.GRADIO_THEME | quote }}
            - name: PYTHONUNBUFFERED
              value: {{ .Values.env.PYTHONUNBUFFERED | quote }}
            - name: YOLO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ include "traffic-report.fullname" . }}-config
                  key: yolo-endpoint
            - name: YOLO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "traffic-report.fullname" . }}-config
                  key: yolo-api-key
            - name: QWEN_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ include "traffic-report.fullname" . }}-config
                  key: qwen-endpoint
            - name: QWEN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "traffic-report.fullname" . }}-config
                  key: qwen-api-key
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}